# Copyright © 2025 Cassidy Spring (Bee).
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Swiftly Swift
author: Cassidy Spring (Bee)
description: Installs Swiftly and a Swift Toolchain.
branding:
  icon: command
  color: orange

inputs:
  swift-version:
    description: Swift Toolchain version that Swiftly will install and use, defaults to latest.
    required: true
    default: latest

runs:
  using: composite
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'macOS' && runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error::Only supports macOS and linux"
        exit 1

    - name: Get Date
      id: date
      shell: bash
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Restore Swiftly - macOS
      if: ${{ runner.os == 'macOS' }}
      uses: actions/cache/restore@v4
      id: restore-swiftly-cache-macos
      with:
        path: swiftly.pkg
        key: swiftly-${{ runner.os }}-${{ runner.arch }}-${{ steps.date.outputs.date }}

    - name: Download Swiftly - macOS
      if: ${{ runner.os == 'macOS' && steps.restore-swiftly-cache-macos.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
        pkgutil --check-signature swiftly.pkg

    - name: Cache Swiftly - macOS
      if: ${{ runner.os == 'macOS' && steps.restore-swiftly-cache-macos.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      id: save-swiftly-cache-macos
      with:
        path: swiftly.pkg
        key: swiftly-${{ runner.os }}-${{ runner.arch }}-${{ steps.date.outputs.date }}

    - name: Install Swiftly - macOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
        ~/.swiftly/bin/swiftly init --verbose --assume-yes --skip-install
        . "${SWIFTLY_HOME_DIR:-$HOME/.swiftly}/env.sh"
        hash -r
        echo "PATH=$PATH" >> $GITHUB_ENV
  
    - name: Restore Swiftly - Linux
      if: ${{ runner.os == 'Linux' }}
      uses: actions/cache/restore@v4
      id: restore-swiftly-cache-linux
      with:
        path: swiftly.tar.gz
        key: swiftly-${{ runner.os }}-${{ runner.arch }}-${{ steps.date.outputs.date }}

    - name: Download Swiftly - Linux
      if: ${{ runner.os == 'Linux' && steps.restore-swiftly-cache-linux.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        curl -o swiftly.tar.gz https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz

    - name: Cache Swiftly - Linux
      if: ${{ runner.os == 'Linux' && steps.restore-swiftly-cache-linux.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      id: save-swiftly-cache-linux
      with:
        path: swiftly.tar.gz
        key: swiftly-${{ runner.os }}-${{ runner.arch }}-${{ steps.date.outputs.date }}

    - name: Install Swiftly - Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        tar -zxf swiftly.tar.gz
        ./swiftly init --verbose --assume-yes --skip-install
        . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh"
        hash -r
        echo "PATH=$PATH" >> $GITHUB_ENV
    
    # NOTE: It feels bad to have sudo statements here but I could not get the post install to work
    # without both of them in place on linux. Neither (and chmod at all) is required on macOS.
    # So this would be nice to dig into more but definitely done for now. 
    - name: Install Swift Toolchain
      shell: bash
      run: |
        swiftly install --use ${{ inputs.swift-version }} --post-install-file=post-install.sh
        if [ -f post-install.sh ]; then
          sudo chmod u+x post-install.sh
          sudo ./post-install.sh
        fi
